### ISSUE TITLE
Move the converation from EXCEL to PANDAS functions from client_controller to the api.

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-flask-client#4]
https://github.com/rcpch/digital-growth-charts-flask-client/blob/420dfb8dab6f85a67d63bc7c1683d732ad5fc981/app.py#L139-L139

**Comment by pacharanero** [comment]
Is this issue still relevant? We have refactored the spreadsheet upload in Flask but the plan is eventually to downgrade the Flask client from active development.
